FROM python:3.8.1-alpine


WORKDIR /usr/src/app

ENV DEBUG 0
ENV DJANGO_ALLOWED_HOSTS shrouded-gorge-18713.herokuapp.com

RUN pip3 install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip3 install -r requirements.txt


COPY . /usr/src/app/

RUN adduser -D myuser
USER myuser

# run gunicorn
CMD gunicorn drf_project.wsgi:application --bind 0.0.0.0:$PORT